plugins {
    id 'com.android.library'
}

android {
    namespace = 'cgeo.geocaching.wherigo'
    compileSdk = 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdk = 26
        targetSdk = 35
    }

    lint {
        // generally we accept lint errors when building
        abortOnError = false

        // abort release builds in case of FATAL errors
        checkReleaseBuilds = true
    }
}

dependencies {
    // Android annotations
    implementation 'androidx.annotation:annotation:1.9.1'

    // Apache Commons Collections - needed for IteratorUtils used in Lua VM
    implementation 'org.apache.commons:commons-collections4:4.5.0'
}
