# Release APK signing
key.store=key.keystore
key.alias=alias
key.store.password=password
key.alias.password=password

# Geocaching.su
su.consumer.key=
su.consumer.secret=

# Geocaching.com public API for Adventure Labs
alc.consumer.key=
